version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    expose:
      - "5000"  # 외부 노출 대신 내부에서만 사용
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"  # 외부 노출은 Nginx만
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

